In [1]:
import time
import numpy as np

In [2]:
x = np.load('data.npy')
x.shape

(10, 50)

In [15]:
friends = np.load('friends.npy')
print(friends)

[['Salman' 'Vahab' 'Mohandes']
 ['Amer' 'Mahmadi' 'Naser']
 ['Abol' 'Moradi' 'eshagh']]


In [30]:
nums = np.ones((10,4), dtype='U5')

In [31]:
nums.dtype

dtype('<U5')

In [43]:
outputs = np.full((3,10),.99)


In [45]:
np.eye(5).shape

(5, 5)

In [46]:
np.diag((10,20,30,40,50,60,70,80,90,100))

array([[ 10,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  20,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  30,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  40,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  50,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  60,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  70,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  80,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  90,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 100]])

In [57]:
np.arange(10,25,)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [93]:
np.linspace(1,100,10, endpoint= False)

array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1])

In [96]:
x = np.linspace(10,100,10)

In [100]:
np.reshape(x, (2,5))

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.]])

In [105]:
np.linspace(10,20,6, endpoint= False).reshape((2,3))

array([[10.        , 11.66666667, 13.33333333],
       [15.        , 16.66666667, 18.33333333]])

In [112]:
np.random.random((10,4))

array([[0.58114307, 0.15404375, 0.11593929, 0.38894673],
       [0.97432878, 0.39938396, 0.25450859, 0.33981111],
       [0.54803792, 0.45564565, 0.61879737, 0.07059034],
       [0.02167092, 0.75540637, 0.47821551, 0.49158596],
       [0.43282138, 0.96499866, 0.73989719, 0.58649734],
       [0.76142475, 0.83475198, 0.46130789, 0.23975755],
       [0.69897432, 0.10641749, 0.9199509 , 0.5652317 ],
       [0.43148107, 0.85925029, 0.50132473, 0.36051547],
       [0.22951859, 0.56035473, 0.00826099, 0.29817068],
       [0.2581137 , 0.48184847, 0.85267147, 0.37639421]])

In [113]:
np.random.randint(5, 10, (10,4))

array([[7, 8, 9, 9],
       [6, 8, 9, 5],
       [5, 8, 9, 7],
       [5, 7, 9, 6],
       [7, 5, 9, 6],
       [5, 6, 8, 5],
       [5, 6, 8, 9],
       [8, 8, 9, 5],
       [6, 9, 6, 6],
       [7, 9, 6, 8]])

In [121]:
x = np.random.normal(1,1.0, (10,4))

In [138]:
(friends == 'Salman').sum()

1

In [128]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.03180926 -0.00288844 -0.12344024 ...  0.15802063 -0.0005713
  -0.05580935]
 [ 0.17578764 -0.09965302  0.1301861  ...  0.09646884 -0.05418697
   0.04731219]
 [ 0.09596869 -0.19797916 -0.03532804 ... -0.03646642  0.03975948
   0.20432181]
 ...
 [-0.02129329 -0.0671486  -0.03518458 ...  0.16281682  0.21021076
  -0.06047743]
 [-0.01081538 -0.18399873 -0.06277455 ... -0.03161296 -0.19330615
   0.14345062]
 [ 0.06720931 -0.05572048 -0.18491306 ...  0.09872919  0.05348298
   0.22296806]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 0.00012271033356755552
The maximum value in X is: 0.4851071462859275
The minimum value in X is: -0.44924760074339765
X has 499484 negative numbers
X has 500516 positive numbers


In [148]:
np.linspace(2,32,16).reshape(4,4)

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])